Aggregation definition: states that it returns a single partial function
w3c/sparql-query pull request #115
Opened 2023-07-26 19:24 UTC by Tpt

Closes #107

2023-07-26 20:48 UTC, TallTed commented
This *changes* the aggregation definition to state that it returns a single partial function.

This does not seem like an editorial change, and this PR does not point back to an issue which is resolved by this change.

Tell us more?

2023-07-27 07:24 UTC, Tpt commented
> this PR does not point back to an issue which is resolved by this change.

It's in the description: #107 (the most relevant part is the end of @hartig's comment). Sorry for not highlighting this more.

> This does not seem like an editorial change
> This changes the aggregation definition to state that it returns a single partial function.

That's a great point. The current spec states that `Aggregate` returns a set of partial function each one having a singleton [domain](https://en.wikipedia.org/wiki/Domain_of_a_function) (i.e. a separate function for each key). This is equivalent to returning a single partial function which domain is all keys returned by the aggregation. And the later is imho a bit simpler and more understandable. Hence this PR.
I considered it to be a editorial change because it does not change anything on how the aggregation is evaluated. But feel free to switch it so substantive if you feel so.

2023-07-27 09:40 UTC, afs commented
I agree this is "editorial". I don't believe it will affect an implementation - no change to tests and no change to an implementation that reported for SPARQL 1.1 (to avoid the problem of saying "any implementation").

2023-07-27 09:57 UTC, afs commented
I looked for other places that may need aligning if `scalarvals` is changing:
The main item is saying what "empty function" is.


I may have missed some - I looked for "scalarvals" and "Aggregation(".

Section "18.2.4.1 Grouping and Aggregation"

The comment says 

> \# note scalarvals may be omitted, then it's equivalent to the empty set

It's not the "empty set" any more.

Section "18.5.1 Aggregate Algebra" (just after the defn box):

> For example, the aggregate expression GROUP_CONCAT(?x ; separator="|") has a scalarvals argument of { "separator" → "|" }.

Is the notation `{ "separator" → "|" }` clear enough? 
I'm happy to keep it as it is and I don't know of an alternative.

The PR change is 

`{ { a -> 1 } , {b -> 2} , { c-> 3} }` becomes `{ a -> 1 , b -> 2 , c-> 3 }`

I haven't found an example in the doc that has multiple mappings.

Section "18.5.1.7 GroupConcat":

> then scalarvals is taken to be the empty function.

No change but do we need to say what "empty function" is in the definition in 18.5.1, or immediately after it?

The example:

> For example, GroupConcat([("a"), ("b"), ("c")], {"separator" → "."}) = "a.b.c".

looks OK - same notation as earlier.

2023-07-27 16:07 UTC, TallTed commented
> [@Tpt] The current spec states that Aggregate returns a set of partial function each one having a singleton [domain](https://en.wikipedia.org/wiki/Domain_of_a_function) (i.e. a separate function for each key). This is equivalent to returning a single partial function which domain is all keys returned by the aggregation.

That helps me. I didn't understand that the new language was effectively equivalent to the old language.

> [@afs] I don't believe it will affect an implementation - no change to tests and no change to an implementation that reported for SPARQL 1.1

And that's the key. Given that the above is so, it doesn't matter to me whether the spec change is actually considered editorial or normative; I'll still be OK with the change.

2023-07-28 20:19 UTC, Tpt commented
@afs Thank you!

> > \# note scalarvals may be omitted, then it's equivalent to the empty set
> It's not the "empty set" any more.

I have replaced this word by "empty function". Thanks!

> Is the notation `{ "separator" → "|" }` clear enough? 
> I'm happy to keep it as it is and I don't know of an alternative.

I agree. It's the one we use in the spec for all "mathematical-like" fonctions including SPARQL solution mappings. And it make the "empty function" definition quite simple (it's just `{}`).

>  The main item is saying what "empty function" is.

Indeed. 

An option for that might be to rephrase in `#defn_algAggregation` <q><i>scalarvals</i> a partial function (possibly empty)</q> to something like <q><i>scalarvals</i> a partial function (possibly empty i.e. `{}`, the function defined on the empty domain)</q> but I am not sure if it is much more helpful. Do you have a better idea?

2023-08-03 21:37 UTC, afs commented
> (possibly empty i.e. {}, the function defined on the empty domain)

Are we going ahead with this change? Looks better to me.

2023-08-03 21:38 UTC, afs approved these changes
One non-blocking comment.

2023-08-04 13:20 UTC, hartig commented on spec/index.html
> +              <i>scalarvals</i> a partial function (possibly empty) passed from the aggregate
```suggestion
              <i>scalarvals</i> a partial function (possibly with an empty domain) passed from the aggregate
```

2023-08-04 13:20 UTC, hartig approved these changes

2023-08-04 20:17 UTC, Tpt commented
>> (possibly empty i.e. {}, the function defined on the empty domain)
> Are we going ahead with this change? Looks better to me.

I have added @hartig suggestion that is fairly similar. Is it ok with you?

2023-08-04 22:17 UTC, TallTed requested changes
The top comment should be treated on its own; the latter 3 suggestions should be treated as one (they're only split because GitHub doesn't let one suggestion include lines that are shown as deleted).

2023-08-04 22:17 UTC, TallTed commented on spec/index.html
> +      # note scalarvals may be omitted, then it's equivalent to the empty function
```suggestion
      # note: scalarvals may be omitted; if so, it's equivalent to the empty function
```

2023-08-04 22:17 UTC, TallTed commented on spec/index.html
>              <p>Let <i>exprlist</i> be a list of expressions or *, <i>func</i> a set function,
```suggestion
            <p>Let <i>exprlist</i> be a list of expressions or `*`; <i>func</i>, a set function;
```

2023-08-04 22:17 UTC, TallTed commented on spec/index.html
>                in the query, and let { key<sub>1</sub>→Ψ<sub>1</sub>, ...,
```suggestion
              <i>scalarvals</i>, a partial function (possibly with an empty domain) passed from the aggregate
              in the query; and { key<sub>1</sub>→Ψ<sub>1</sub>, ...,
```

2023-08-04 22:17 UTC, TallTed commented on spec/index.html
>                single value for each key and group of solutions for that key.</p>
```suggestion
              key<sub>m</sub>→Ψ<sub>m</sub> }, a partial function from keys to
              solution sequences as produced by the grouping step.</p>
            <p>Aggregation applies the set function `func` to the given set and produces a
              single value for each key and a group of solutions for that key.</p>
```

2023-08-17 16:16 UTC, merged

2023-08-17 16:25 UTC, kasei commented
Thanks, @Tpt . Was planning on merging this today :D