errata-query-9 (#30)
w3c/sparql-query pull request #30
Opened 2023-03-22 21:28 UTC by afs

Fix an example.

See [public-sparql-dev/2014OctDec/0005](https://lists.w3.org/Archives/Public/public-sparql-dev/2014OctDec/0005.html).

2023-03-23 18:13 UTC, hartig approved these changes
With the current rendering, it is a bit tricky to see that the example now contains two separate `Extend( ... )` expressions that represent the two steps. However, assuming we would use a CSS style similar to the one in SPARQL-QUERY-1.1, then the separation will be visible. So, I approve this PR.

2023-03-23 18:44 UTC, afs commented
The preview doesn't get the formatting right (I guess it is not processing `local.css`).

We need to discuss format at sometime. reSpec defaults give a significantly different appearance. They make it look like the document has changed content-wise when it hasn't and also they don't work very well.

I'm prioritizing errata for FPWD. (It won't be all errata.)

At some time, all the formatting needs converting to systematic use of reSpec.
It is hard to reformat PRs and have errata PRs open at the same time.

It should look like (this is taken from viewing the local file in the browser). There is a correction - it was missing one of the before-simplify parts. This time, I used a program to generate the algebra content.

----

![image](https://user-images.githubusercontent.com/101362/227314259-63043a91-e5c4-45af-b7cf-d3fec52da9b2.png)

2023-03-27 08:48 UTC, rubensworks requested changes

2023-03-27 08:48 UTC, rubensworks commented on spec/index.html
> +              &nbsp;&nbsp; ?v2, 2*?v)<br>
```suggestion
              &nbsp;&nbsp; ?v2, 2*?v<br>
```

2023-03-27 13:38 UTC, afs commented
@rubensworks - fixes applied.

2023-03-27 18:31 UTC, domel approved these changes

2023-03-28 13:57 UTC, merged