Fix data cite issues and code snippets
w3c/sparql-query pull request #45
Opened 2023-03-30 12:37 UTC by rubensworks

Closes #14

***
<a href="https://pr-preview.s3.amazonaws.com/w3c/sparql-query/pull/45.html" title="Last updated on Apr 7, 2023, 10:43 AM UTC (0e8b8bd)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/sparql-query/45/e3b9d77...0e8b8bd.html" title="Last updated on Apr 7, 2023, 10:43 AM UTC (0e8b8bd)">Diff</a>

2023-03-31 12:20 UTC, afs requested changes
2 small suggestions but otherwise LGTM.

2023-03-31 12:20 UTC, afs commented on spec/index.html
> +        <p>SPARQL 1.2 allows to create values from complex expressions. The queries below show how to
```suggestion
        <p>SPARQL 1.2 allows values to be created from complex expressions. The queries below show how to
```

2023-03-31 12:20 UTC, afs commented on spec/index.html
> +                                           "RDF12-XML#">RDF/XML</a> as:</p>
```suggestion
          <p>which can be serialized in <a data-cite="RDF12-XML#">RDF/XML</a> as:</p>
```

2023-03-31 16:28 UTC, hartig approved these changes

2023-03-31 20:00 UTC, TallTed commented on spec/index.html
> +        <p>SPARQL 1.2 allows values to be created from complex expressions. The queries below show how to
```suggestion
        <p>SPARQL 1.2 allows values to be created from complex expressions. The queries below show how
```

2023-04-02 08:09 UTC, afs approved these changes

2023-04-03 12:48 UTC, domel approved these changes

2023-04-07 10:44 UTC, merged