Harmonizes reference to XML Schema Part 2: Datatypes
w3c/sparql-query pull request #85
Opened 2023-05-27 13:51 UTC by Tpt

Avoids to point either to the section either to the definition

2023-05-27 14:45 UTC, hartig approved these changes

2023-05-27 17:32 UTC, afs commented
Issue https://github.com/w3c/sparql-query/issues/49.

RDF Concepts (RDF 1.1) references XML Schema 1.1.

See:
https://www.w3.org/TR/xmlschema11-2/#changes.
with IEEE 754 and F&O alignment and it's F&O that defines the relevant SPARQL functions anyway.

> this allows better alignment with the treatment of such values in "XQuery 1.0 and XPath 2.0 Functions and Operators".

See their reference:
https://www.w3.org/TR/xmlschema11-2/#F_O

The sparql-query doc actually has a mix because other references have been to xpath-functions (F&O) -- this tracks latest (hence is 3.1 ATM).

Conclusion: We should consolidate on XML Schema 1.1.

2023-05-27 17:32 UTC, afs requested changes

2023-05-27 17:32 UTC, afs commented on spec/index.html
> +          <a data-cite="XMLSCHEMA-2#dt-atomic">atomic datatype</a> corresponding to the
`XMLSCHEMA-2` is XML schema 1.0.

```suggestion
          <a data-cite="XMLSCHEMA11-2#dt-atomic">atomic datatype</a> corresponding to the
```
which goes to http://www.w3.org/TR/xmlschema11-2#dt-atomic

2023-05-27 17:32 UTC, afs commented on spec/index.html
> +            str = <a data-cite="XMLSCHEMA-2#dt-string">xsd:string</a><br>
```suggestion
          <p>bool = <a data-cite="XMLSCHEMA11-2#dt-boolean">xsd:boolean</a><br>
            dbl = <a data-cite="XMLSCHEMA11-2#dt-double">xsd:double</a><br>
            flt = <a data-cite="XMLSCHEMA11-2#dt-float">xsd:float</a><br>
            dec = <a data-cite="XMLSCHEMA11-2#dt-decimal">xsd:decimal</a><br>
            int = <a data-cite="XMLSCHEMA11-2#dt-integer">xsd:integer</a><br>
            dT = <a data-cite="XMLSCHEMA11-2#dt-dateTime">xsd:dateTime</a><br>
            str = <a data-cite="XMLSCHEMA11-2#dt-string">xsd:string</a><br>
```

2023-05-27 17:32 UTC, afs commented on spec/index.html
> +          <a data-cite="XMLSCHEMA-2#dt-regex">XML Schema Regular Expressions</a>.</p>
```suggestion
          <a data-cite="XMLSCHEMA11-2#dt-regex">XML Schema Regular Expressions</a>.</p>
```

2023-05-27 17:57 UTC, Tpt commented
@afs Thank you for raising this. I was considering doing the update in a followup PR to separate the "editorial" change to the "substantive" change. But fine with me in this PR. I have updated the PR with moving all XSD references to 1.1

2023-05-28 15:18 UTC, afs approved these changes

2023-05-28 19:28 UTC, domel approved these changes

2023-05-29 10:42 UTC, rubensworks approved these changes

2023-06-29 16:47 UTC, merged